name: Python Tests

on:
  push:
    branches: [master]
    paths:
      - "**/*.py"
      - "requirements.txt"
      - "pyproject.toml"
      - ".github/workflows/python-tests.yml"
  pull_request:
    branches: [master]
    paths:
      - "**/*.py"
      - "requirements.txt"
      - "pyproject.toml"
      - ".github/workflows/python-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[dev]

      - name: Lint with ruff
        run: |
          ruff check .

      - name: Type check with mypy
        run: |
          mypy .

      - name: Test with pytest
        run: |
          pytest
