name: YAML Validation

on:
  push:
    branches: [master]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    branches: [master]
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint --config-file .yamllint.yml . || ([ ! -f .yamllint.yml ] && yamllint .)
